# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        test-kind: ['unit-tests']
    steps:
      - uses: actions/checkout@v2
      - name: Run test "${{ matrix.test-kind }}"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --immutable --immutable-cache
      - run: yarn tsc-check
      - run: yarn ${{ matrix.test-kind }}
  check-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --immutable --immutable-cache --check-cache
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint, Tsc and Formatting
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install --immutable --immutable-cache
      - run: yarn lint
  tests-e2e:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.22.2-focal
    strategy:
      matrix:
        test-kind: ['g:e2e --shard=1/1']
    steps:
      - uses: actions/checkout@v3
      - name: Set git safe directory
        # This is added as a fix for https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run e2e tests "${{ matrix.test-kind }}"
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: yarn install
        run: yarn install --immutable --immutable-cache
      - name: Install playwright dependencies
        run: yarn g:playwright-dep
      - run: yarn ${{ matrix.test-kind }}
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: playwright trace
          path: tooling/playwright-e2e/
          retention-days: 3
